region_pbf:
  [
    "https://download.geofabrik.de/europe/great-britain/england/greater-london-latest.osm.pbf",
    "https://download.geofabrik.de/europe/great-britain/england/hertfordshire-latest.osm.pbf",
    "https://download.geofabrik.de/europe/great-britain/england/essex-latest.osm.pbf",
    "https://download.geofabrik.de/europe/great-britain/england/kent-latest.osm.pbf",
    "https://download.geofabrik.de/europe/great-britain/england/surrey-latest.osm.pbf",
    "https://download.geofabrik.de/europe/great-britain/england/buckinghamshire-latest.osm.pbf",
    "https://download.geofabrik.de/europe/great-britain/england/berkshire-latest.osm.pbf"
  ]

collection:
  osm_tags:
    amenity: [True]
    landuse: [True]
    leisure: [True]
    tourism: [True]
    natural: [True]
    
  additional_columns:
    [
    ]
  nodes: False
  ways: True
  relations: False

preparation: