# VARIABLES_SET 
VARIABLES_SET : 
  db_schema: "https://s3.eu-central-1.amazonaws.com/goat-db-schemas/main/dump.tar"
  landuse:
    region_pbf : [
      "https://download.geofabrik.de/europe/germany/saarland-latest.osm.pbf" 
    ]
    collection:
        # add all tags in a list associated to their osm feature that should be collected from geofabrik 
        # if you are not sure add feature not_sure: ["tag1", "tag2"] then a dict with all tags (value) and their assosicated feature (key) and one key 
        # -> use e.g. terminal and activate your env -> change directory to src (run: cd src) 
        # -> and run: python -c "from collection import classify_osm_tags;classify_osm_tags('landuse')" for e.g. landuse
        # "not a valid osm tag/ missing in our list" with values that where not found will be returned and the collection breaks
        # -> if you need a certain tag add it manually to osm_featutre_tags_dict.py
        # If you want all entries of a feature use True -> PyrOSM does not apply a filter
        # If you want the data filtered by all tags in our dict -> use "all"
        # a list of the most used tags and their associated feature can be seen in osm_feature_tags_dict.py or https://wiki.openstreetmap.org/wiki/Map_features,
        # https://taginfo.openstreetmap.org/keys/tourism#values  
        # the resulting dataformat e.g. pandas geodataframe will have a column for every feature and one for every entry in additional_columns (should be OSM
        # features as well)
        # if you do not want to add any additional columns, an empty list [] is still needed

      osm_tags:
        landuse: ["basin", "reservoir", "salt_pond", "water", "waters", "allotments", "aquaculture", "farmland", "farmyard", "greenhouse_horticulture",  
                  "plant_nursery", "vineyard", "forest", "grass", "meadow", "village_green", "recreation_ground", "cemetery", "residential", "garages",
                  "commercial", "retail", "religious", "industrial", "landfill", "quarry", "railway", "highway", "military", "garden", "national_park", 
                  "nature_reserve", "park", "grave_yard", "orchard", "fallow", "plantation"] 
        amenity: ["parking", "school", "hospital"]
        leisure: ["adult_gaming_centre", "amusement_arcade", "beach_resort", "bandstand", "dance", "dog_park", "escape_game", "fitness_centre",
                  "garden", "horse_riding", "marina", "miniature_golf", "nature_reserve", "park", "pitch", "playground", "sports_centre", "stadium",
                  "swimming_pool", "track", "water_park", "leisure"]
        natural: ["water", "scrub", "wood", "wetland", "grassland", "heath"]

      additional_columns: ["tourism", "name"]

      # define which geometry types should be collected from OSM (do not turn off lines -> not all data will be collected) 
      nodes : True
      ways : True
      relations : True

    preparation:
      region_pbf :
        # put all osm_tags from the collection into a category of landuse_simplified as well -> new column landuse_simplified with grouped tags
      landuse_simplified : 
        water          : ["basin","reservoir","salt_pond","waters", "swimming_pool"]
        agriculture    : ["allotments", "aquaculture", "fallow", "farmland", "farmyard", "greenhouse_horticulture", "orchard", "pasture", "plant_nursery", 
                          "plantation", "vineyard"]
        nature         : ["forest","grass","meadow","green_area", "wetland", "scrub", "wood", "grassland", "heath"]
        leisure        : ["adult_gaming_centre", "amusement_arcade", "beach_resort", "bandstand", "dance", "dog_park", "escape_game", "fitness_centre", 
                          "garden", "horse_riding", "marina", "miniature_golf", "nature_reserve", "park", "pitch", "playground", "sports_centre", "stadium",  
                          "track", "water_park", "national_park", "village_green", "recreation_ground"]
        cemetery       : ["grave_yard"]
        residential    : ["garages"]
        commercial     : ["retail"]
        community      : ["school","university","hospital","college","churchyard","religious"]
        industrial     : ["landfill","quarry"]
        transportation : ["highway","parking","railway", "parking"]
        military       : []

    fusion: 
    update :
  
  pois:
    region_pbf : [
      "https://s3.eu-central-1.amazonaws.com/goat-db-schemas/osm_raw_data/deerfield-latest.osm.pbf"
    ]
    collection:
      osm_tags:
        amenity : ["fuel", "post_office", "taxi", "atm", "bank", "dentist", "doctors", "pharmacy", "post_box", "marketplace", "bar", "biergarten", "cafe", 
                   "pub", "fast_food", "ice_cream", "restaurant", "theatre", "cinema", "library", "nightclub", "recycling", "car_sharing", "bicycle_rental", 
                   "charging_station", "bus_station", "bench"]
        shop    : ["clothes", "convenience", "general", "fashion", "fuel", "bakery", "butcher", "florist", "greengrocer", "kiosk", "mall", "shoes", "sports", 
                   "supermarket", "hairdresser", "health_food", "chemist", "ice_cream"]
        tourism : ["hotel", "museum", "hostel", "guest_house", "viewpoint", "gallery"]
        railway : ["station", "platform", "stop", "tram_stop", "subway_entrance"]
        leisure : ["playground", "fitness_station", "water_park", "pitch", "sports_centre", 'sports_hall', "fitness_centre"]
        sport   : ["yoga", "fitness"]
        highway : ["bus_stop"]
        public_transport : ["stop_position", "station"]

      additional_columns: ["name", "brand", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "website", 
                           "opening_hours", "operator", "origin", "organic", "subway"]
      nodes : True
      ways : True
      relations : True
      
    preparation:
      bank: 
        sparkasse       : ["kreissparkasse", "sparkasse", "stadtsparkasse"]
        raiffeisenbank  : ["raiffeisenbank", "vr bank", "vr-bank", "volksbank", "volks", "münchner"]
        hypovereinsbank : ["hypo vereinsbank", "hypovereinsbank"]
        commerzbank : ["commerzbank"]

      chemist: 
        dm       : ["dm"]
        rossmann : ["rossmann"]
        müller   : ["müller", "mueller"] 

      fast_food: 
        mcdonalds : ["mcdonald"]
      
      organic :
        denn's Biomarkt : ["denn's", "denns", "denn"]
        alnatura : ["alnatura"]
  
      health_food: 
        vitalia   : ["vitalia"]
        reformhaus : ["reformhaus"]

      hypermarket: 
        hit       : ["hit"]
        real      : ["real"]
        v-markt   : ["v-markt"]
        kaufland  : ["kaufland"]
        marktkauf : ["marktkauf"]
  
      supermarket: 
        rewe     : ["rewe", "rewe city"]
        tegut    : ["tegut"]
        feneberg : ["feneberg"]
        nahkauf  : ["nahkauf"]
        kupsch   : ["kupsch"]
        aez      : ["aez"]

      discount_gym: 
        fitx           : ["fitx"]
        mcfit          : ["mcfit"]
        fitstar        : ["fitstar","fit-star", "fit star"]
        cleverfit      : ["cleverfit" ,"clever fit"]
        jumpersfitness : ["jumpersfitness" ,"jumpers fitness"]
  
      discount_supermarket: 
        aldi  : ["aldi"]
        lidl  : ["lidl"]
        netto : ["netto"]
        norma : ["norma"]
        penny : ["penny"]
    
      no_end_consumer_store: 
        metro     : ["metro"]
        hamberger : ["hamberger"]
    
      community_sport_centre: ["bezirkssportanlage"]

      # Not used (operators for various cities in Germany are too different)
      operators_bicycle_rental: ["münchner verkehrs gesellschaft", "münchner verkehrsgesellschaft", "mvg"]
    
      sport:
        sport_var_disc   : ["table_tennis"]
        leisure_var_add  : ["sports_hall", "fitness_center", "sport_center", "track", "pitch"]
        leisure_var_disc : ["fitness_station"]
      
      # Schools config relevant for preparation separate file and subsequent fusion of file
      schools:
        schule: ['Grundschule','Gymnasium','Realschule','Werkrealschule']
        grundschule: ['Grund- und Teilhauptschule','Grund- und Hauptschule','Grund- und Mittelschule']
        hauptschule_mittelschule : ['Grund- und Teilhauptschule','Grund- und Hauptschule','Hauptschule','Mittelschule','Grund- und Mittelschule']
        exclude: ['privat','priv.','montessori','waldorf']

    replace:
      table_name: "poi_custom_deerfield"
      pois_categories: []

    update :
      rs_set:  ['083110000'] 
      categories : ['tram_stop', 'bus_stop']


  # config to collect buildings from OSM
  buildings :
    region_pbf: [
      "https://download.geofabrik.de/europe/germany/saarland-latest.osm.pbf" , 
      "https://download.geofabrik.de/europe/germany/rheinland-pfalz-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf", 
      "https://download.geofabrik.de/europe/germany/bayern-latest.osm.pbf", 
      "https://download.geofabrik.de/europe/germany/brandenburg-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/sachsen-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/sachsen-anhalt-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/thueringen-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/hamburg-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/niedersachsen-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/schleswig-holstein-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/nordrhein-westfalen-latest.osm.pbf",
      "https://download.geofabrik.de/europe/germany/hessen-latest.osm.pbf"
    ]
    collection:
      osm_tags: 
        building: [True]
      additional_columns : ["amenity", "leisure", "addr:street", "addr:housenumber", "building:levels", "roof:levels"]
      nodes : False
      ways : True
      relations : False

    preparation:
    fusion:
    update :

  # Variable container to perform the population scripts      
  population:
    region_pbf: ["Mittelfranken","Niederbayern","Oberbayern","Oberfranken","Oberpfalz","Schwaben","Unterfranken"]
    collection:
    preparation:
      rs_codes : [] 
      average_building_levels: '4'
      average_roof_levels: '1'
      average_height_per_level: '3.5'
      building_types_residential: ["apartments", "bungalow", "detached", "dormitory", "residential", "house", "terrace", "home", "semidetached_house"]
      minimum_building_size_residential: '30'
      custom_landuse_no_residents: ["AX_TagebauGrubeSteinbruch", "AX_SportFreizeitUndErholungsflaeche", "AX_FlaecheBesondererFunktionalerPraegung",
                                    "AX_BauwerkOderAnlageFuerSportFreizeitUndErholung", "AX_Halde", "AX_Friedhof", "AX_IndustrieUndGewerbeflaeche",
                                    "AX_Landwirtschaft", "AX_Wald", "AX_Gehoelz", "AX_Heide", "AX_Moor", "AX_Insel", "AX_Sumpf", 
                                    "AX_UnlandVegetationsloseFlaeche", "AX_Vegetationsmerkmal", "AX_Bahnverkehr", "AX_Platz", "AX_Strassenverkehr",
                                    "AX_Flugverkehr", "AX_Fließgewaesser", "AX_Hafenbecken", "AX_StehendesGewaesser"]
      custom_landuse_potential_residents: ["AX_FlaecheGemischterNutzung"]
      custom_landuse_additional_no_residents: ["Water", "Permanent crops (vineyards, fruit trees, olive groves)", "Railways and associated land",
                                              "Herbaceous vegetation associations (natural grassland, moors...)", "Forests",
                                              "Sports and leisure facilities", "Other roads and associated land", "Green urban areas",
                                              "Arable land (annual crops)", "Fast transit roads and associated land", 
                                              "Industrial, commercial, public, military and private units", "Mineral extraction and dump sites",
                                              "Pastures"]
      custom_landuse_additional_potential_residents: ["Construction sites","Continuous urban fabric (S.L. : > 80%)","Discontinuous dense urban fabric (S.L. : 50% -  80%)",
      "Discontinuous low density urban fabric (S.L. : 10% - 30%)","Discontinuous medium density urban fabric (S.L. : 30% - 50%)","Discontinuous very low density urban fabric (S.L. : < 10%)",
      "Isolated structures","Land without current use"]
      osm_landuse_no_residents: ["farmyard","construction","farmland","quarry","industrial","retail","commercial","forest","military", "cemetery",
                                "landfill","allotments","recreation ground","railway","parking","grass","grassland","green","garages"]
      tourism_no_residents: ["zoo"]
      amenity_no_residents: ["hospital","university","community_centre","school","kindergarten","recreation_ground","wood"]
      one_meter_degree: '0.000009'
      compute_slope_impedance: "'no'"
      average_gross_living_area: '50'
      census_minimum_number_new_buildings: '1'
    fusion:
    update :

  # temporary variable container to generate ways table
  ways:
    region_pbf: [
      http://download.geofabrik.de/north-america/us/florida-latest.osm.pbf
      #https://s3.eu-central-1.amazonaws.com/goat-db-schemas/osm_raw_data/deerfield-latest.osm.pbf
      #"https://download.geofabrik.de/europe/germany/saarland-latest.osm.pbf" , 
      #"https://download.geofabrik.de/europe/germany/rheinland-pfalz-latest.osm.pbf" #,
      # "https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf", 
      # "https://download.geofabrik.de/europe/germany/bayern-latest.osm.pbf", 
      # "https://download.geofabrik.de/europe/germany/brandenburg-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/sachsen-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/sachsen-anhalt-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/thueringen-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/hamburg-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/niedersachsen-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/schleswig-holstein-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/nordrhein-westfalen-latest.osm.pbf",
      # "https://download.geofabrik.de/europe/germany/hessen-latest.osm.pbf"
    ]
    region_pbf_r5: "http://download.openstreetmap.fr/extracts/europe/germany-latest.osm.pbf"
    collection: 
    preparation:
      excluded_class_id_walking: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
      excluded_class_id_cycling: [0,101,102,103,104,105,106,107,501,502,503,504,701,801]
      categories_no_foot: ["use_sidepath","no"]
      categories_no_bicycle: ["use_sidepath"]
      compute_slope_impedance: "'no'"
      wheelchair:
        smoothness_no: ["very_bad","horrible","very_horrible","impassable"]
        smoothness_limited: ['bad']
        surface_no: ['ground','grass','sand','dirt','unhewn_cobblestone','unpaved']
        surface_limited: ['gravel']
        highway_onstreet_yes: ['living_street']
        highway_onstreet_limited: ['residential','service']
      categories_sidewalk_no_foot: ["separate"]
      cycling_surface:
        paving_stones: '0.2'
        sett: '0.3'
        unhewn_cobblestone: '0.3'
        cobblestone: '0.3'
        pebblestone: '0.3'
        unpaved: '0.2'
        compacted: '0.05'
        fine_gravel: '0.05'
        gravel: '0.3'
        sand: '0.4'
        grass: '0.25'
        mud: '0.4'
      one_meter_degree : 0.000009
      node_previous_id: 8397587
      edge_previous_id: 25299063