version: "3.9"
networks:
  data_preparation_proxy:

volumes:
  3dcity_db:

services:
  3dcity:
    image: 3dcitydb/3dcitydb-pg
    command: postgres -c 'config_file=/etc/postgresql.conf'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_3DCITY}
      - POSTGRES_USER=${POSTGRES_USER_3DCITY}
      - POSTGRES_DB=${POSTGRES_DB_3DCITY}
      - POSTGIS_SFCGAL_3DCITY=true
      - SRID=${SRID}
      - HEIGHT_EPSG=${HEIGHT_EPSG}
      - GMLSRSNAME=${GMLSRSNAME}

    ports:
      - "${POSTGRES_OUTER_PORT_3DCITY}:5432"
    volumes:
      - 3dcity_db:/var/lib/postgresql
      - ${PWD}/postgresql.conf:/etc/postgresql.conf
    restart: on-failure
