region_pbf : [
  "https://download.geofabrik.de/europe/germany/saarland-latest.osm.pbf" 
]
collection:
    # add all tags in a list associated to their osm feature that should be collected from geofabrik 
    # if you are not sure add feature not_sure: ["tag1", "tag2"] then a dict with all tags (value) and their assosicated feature (key) and one key 
    # -> use e.g. terminal and activate your env -> change directory to src (run: cd src) 
    # -> and run: python -c "from collection import classify_osm_tags;classify_osm_tags('landuse')" for e.g. landuse
    # "not a valid osm tag/ missing in our list" with values that where not found will be returned and the collection breaks
    # -> if you need a certain tag add it manually to osm_featutre_tags_dict.py
    # If you want all entries of a feature use True -> PyrOSM does not apply a filter
    # If you want the data filtered by all tags in our dict -> use "all"
    # a list of the most used tags and their associated feature can be seen in osm_feature_tags_dict.py or https://wiki.openstreetmap.org/wiki/Map_features,
    # https://taginfo.openstreetmap.org/keys/tourism#values  
    # the resulting dataformat e.g. pandas geodataframe will have a column for every feature and one for every entry in additional_columns (should be OSM
    # features as well)
    # if you do not want to add any additional columns, an empty list [] is still needed

  osm_tags:
    landuse: ["basin", "reservoir", "salt_pond", "water", "waters", "allotments", "aquaculture", "farmland", "farmyard", "greenhouse_horticulture",  
              "plant_nursery", "vineyard", "forest", "grass", "meadow", "village_green", "recreation_ground", "cemetery", "residential", "garages",
              "commercial", "retail", "religious", "industrial", "landfill", "quarry", "railway", "highway", "military", "garden", "national_park", 
              "nature_reserve", "park", "grave_yard", "orchard", "fallow", "plantation"] 
    amenity: ["parking", "school", "hospital"]
    leisure: ["adult_gaming_centre", "amusement_arcade", "beach_resort", "bandstand", "dance", "dog_park", "escape_game", "fitness_centre",
              "garden", "horse_riding", "marina", "miniature_golf", "nature_reserve", "park", "pitch", "playground", "sports_centre", "stadium",
              "swimming_pool", "track", "water_park", "leisure"]
    natural: ["water", "scrub", "wood", "wetland", "grassland", "heath"]

  additional_columns: ["tourism", "name"]

  # define which geometry types should be collected from OSM (do not turn off lines -> not all data will be collected) 
  nodes : True
  ways : True
  relations : True

preparation:
  region_pbf :
    # put all osm_tags from the collection into a category of landuse_simplified as well -> new column landuse_simplified with grouped tags
  landuse_simplified : 
    water          : ["basin","reservoir","salt_pond","waters", "swimming_pool"]
    agriculture    : ["allotments", "aquaculture", "fallow", "farmland", "farmyard", "greenhouse_horticulture", "orchard", "pasture", "plant_nursery", 
                      "plantation", "vineyard"]
    nature         : ["forest","grass","meadow","green_area", "wetland", "scrub", "wood", "grassland", "heath"]
    leisure        : ["adult_gaming_centre", "amusement_arcade", "beach_resort", "bandstand", "dance", "dog_park", "escape_game", "fitness_centre", 
                      "garden", "horse_riding", "marina", "miniature_golf", "nature_reserve", "park", "pitch", "playground", "sports_centre", "stadium",  
                      "track", "water_park", "national_park", "village_green", "recreation_ground"]
    cemetery       : ["grave_yard"]
    residential    : ["garages"]
    commercial     : ["retail"]
    community      : ["school","university","hospital","college","churchyard","religious"]
    industrial     : ["landfill","quarry"]
    transportation : ["highway","parking","railway", "parking"]
    military       : []
